# Task 4
This serves as a template which will guide you through the implementation of this task. It is advised to first read the whole template and get a sense of the overall structure of the code before trying to fill in any of the TODO gaps.
This is the jupyter notebook version of the template. For the python file version, please refer to the file `template_solution.py`.

First, we import necessary libraries:

In [1]:
import os
# We disable low-level log outputs by default to keep the terminal clean
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import pandas as pd
import numpy as np
from tqdm import tqdm
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
# Add any other imports you need here

Depending on your approach, you might need to adapt the structure of this template or parts not marked by TODOs.
It is not necessary to completely follow this template. Feel free to add more code and delete any parts that are not required.

In [3]:
DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 64  # TODO: Set the batch size according to both training performance and available memory
NUM_EPOCHS = 5  # TODO: Set the number of epochs

train_val = pd.read_csv("train.csv")
test_val = pd.read_csv("test_no_score.csv")

In [4]:
train_val.head(10)

,title,sentence,score
0,A strange album,This one is a bit strange. On one hand I think...,1
1,Tales of King Arthur,The books were received in a timely manner. I ...,1
2,Great Tribute to the Boykin Spaniel,This is a great book to share with your childr...,1
3,A Bit of a Disappointment,I think Phil's ego filled up most of the pages...,0
4,Compare I know what I saw/ with Out of the blu...,I recently purchased these two dvd's. It was a...,0
5,Stevie and his band are incredible!,"I ordered this DVD with a bunch of other ""Funk...",1
6,Silence of the North,I was thrilled to find this movie I was lookin...,1
7,"The cover and paper quality, and graph color a...",The book's content is rich and meaningful. But...,0
8,Iron Man 2 Review,Not as good as the first Iron Man. Iron Man 2 ...,0
9,Cream - 'I Feel Free: Ultimate Cream' (Polydor),A superb 23 track collection of Cream's repert...,1

In [5]:
test_val.head()

,title,sentence
0,Give it time,"If you are looking for another Murmer, look so..."
1,"Useless, with the exception of checking your e...","As others have stated, this device is USB 1.1,..."
2,The Album That Started It All For Martina...,Still one of my favorite Martina albums.This i...
3,Not up to some other versions,This production of the classic was just okay. ...
4,Great CD,This cd has a good selection of Prince great h...

In [ ]:
# TODO: Fill out SentimentDataset
class SentimentDataset(Dataset):
    def __init__(self, texts, labels=None):
        pass

    def __len__(self):
        pass

    def __getitem__(self, index):
        # TODO: Tokenize and return a {input_ids, attention_mask, labels} dictionary, or just {input_ids, attention_mask} for test data.
        pass

In [ ]:
train_dataset = SentimentDataset(train_val["text"].tolist(), train_val["label"].tolist())
test_dataset = SentimentDataset(test_val["text"].tolist())

train_loader = DataLoader(dataset=train_dataset,
                          batch_size=BATCH_SIZE,
                          shuffle=True,
                          num_workers=4,         # If you want to utilize multi-processing, set this to the number of your available cores!
                          pin_memory=True)
test_loader = DataLoader(dataset=test_dataset,
                         batch_size=BATCH_SIZE,
                         shuffle=False,
                         num_workers=4,          # If you want to utilize multi-processing, set this to the number of your available cores!
                         pin_memory=True)
# Additional code if needed

In [ ]:
# TODO: Fill out SentimentClassifier
class SentimentClassifier(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x


model = SentimentClassifier().to(DEVICE)

In [ ]:
# TODO: Setup loss function, optimizer, and scheduler
criterion = None
optimizer = None
scheduler = None

model.train()
for epoch in range(NUM_EPOCHS):
    model.train()
    for batch in tqdm(train_loader, total=len(train_loader)):
        batch = {k: v.to(DEVICE) for k, v in batch.items()}

        # TODO: Set up training loop

In [ ]:
model.eval()
with torch.no_grad():
    results = []
    for batch in tqdm(test_loader, total=len(test_loader)):
        batch = {k: v.to(DEVICE) for k, v in batch.items()}

        # TODO: Set up evaluation loop

    with open("result.txt", "w") as f:
        for val in np.concatenate(results):
            f.write(f"{val}\n")